"""
SUMO/TraCI traffic environment — mirrors the CityFlow TrafficEnv interface.

Prerequisites:
    1. pip install traci sumolib       (already installed)
    2. brew install sumo               (installs the simulator binary)
    3. cd data/sumo && bash setup_sumo.sh   (generates cross.net.xml via netconvert)

State (11 dims):  [veh_N, veh_S, veh_E, veh_W,
                   wait_N, wait_S, wait_E, wait_W,
                   total_veh, total_wait, current_phase]
Action:           0 = NS green,  1 = EW green
Reward:           same formulation as CityFlow env for fair comparison
"""

import os
import subprocess  # noqa: F401 — used for subprocess.DEVNULL in traci.start
import sys
import warnings

import numpy as np

try:
    import traci
except ImportError:
    raise ImportError("traci not found. Install with: pip install traci sumolib")

# ── Paths ─────────────────────────────────────────────────────────────────────
_DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "sumo")
_NET_FILE  = os.path.join(_DATA_DIR, "cross.net.xml")
_CFG_FILE  = os.path.join(_DATA_DIR, "cross.sumocfg")

# Phase indices as generated by netconvert for a simple cross intersection
# 0 = NS green, 1 = NS yellow, 2 = EW green, 3 = EW yellow
_PHASE_NS_GREEN  = 0
_PHASE_NS_YELLOW = 1
_PHASE_EW_GREEN  = 2
_PHASE_EW_YELLOW = 3
_YELLOW_STEPS    = 3     # 3 sim-seconds of yellow on phase switch

# Approach edge IDs (must match cross.edg.xml)
_APPROACHES = ["N2C", "S2C", "E2C", "W2C"]


class SumoTrafficEnv:
    def __init__(
        self,
        cfg_file: str = None,
        tl_id:    str = "C",
        use_gui:  bool = False,
        action_duration: int = 10,
        delay_ms: int = 0,
        gui_settings_file: str = None,
    ):
        self.cfg_file        = cfg_file or _CFG_FILE
        self.tl_id           = tl_id
        self.use_gui         = use_gui
        self.action_duration = action_duration
        self.gui_settings_file = gui_settings_file

        self.current_phase       = 0
        self.prev_total_waiting  = 0.0
        self._sumo_running       = False
        self._delay_ms           = delay_ms
        self._arrived_total      = 0   # cumulative throughput tracker

        # Verify network exists
        if not os.path.exists(_NET_FILE):
            raise FileNotFoundError(
                f"SUMO network not found at {_NET_FILE}\n"
                "Generate it with:\n"
                "  cd data/sumo && bash setup_sumo.sh\n"
                "(requires: brew install sumo)"
            )

        # Locate the sumo binary and resolve SUMO_HOME
        import glob as _glob
        binary = "sumo-gui" if use_gui else "sumo"
        # Discover any installed SUMO version under the macOS framework path
        _versioned = _glob.glob(
            "/Library/Frameworks/EclipseSUMO.framework/Versions/*/EclipseSUMO"
        )
        _SUMO_SEARCH = [
            os.environ.get("SUMO_HOME", ""),
            "/Library/Frameworks/EclipseSUMO.framework/Versions/Current/EclipseSUMO",
        ] + sorted(_versioned, reverse=True) + [
            "/opt/homebrew/share/sumo",
            "/usr/local/share/sumo",
        ]
        self._sumo_bin  = binary   # fallback: rely on PATH
        self._sumo_home = os.environ.get("SUMO_HOME", "")
        for candidate_home in _SUMO_SEARCH:
            if candidate_home and os.path.isfile(os.path.join(candidate_home, "bin", binary)):
                self._sumo_bin  = os.path.join(candidate_home, "bin", binary)
                self._sumo_home = candidate_home
                break

    # ── Lifecycle ────────────────────────────────────────────────────────────

    def _start_sumo(self):
        if self._sumo_running:
            try:
                traci.close()
            except Exception:
                pass
            self._sumo_running = False

        # Set SUMO_HOME in the current process so the subprocess inherits it
        if self._sumo_home:
            os.environ["SUMO_HOME"] = self._sumo_home

        def _build_cmd(bin_path: str):
            cmd = [
                bin_path,
                "-c", self.cfg_file,
                "--no-warnings",
                "--no-step-log",
                "--time-to-teleport", "-1",
            ]
            if self.use_gui and self.gui_settings_file and os.path.exists(self.gui_settings_file):
                cmd += ["--gui-settings-file", self.gui_settings_file]
            if self._delay_ms > 0:
                cmd += ["--delay", str(self._delay_ms)]
            return cmd

        cmd = _build_cmd(self._sumo_bin)
        old_display = os.environ.get("DISPLAY")
        clear_display = bool(self.use_gui and sys.platform == "darwin" and old_display)
        try:
            if clear_display:
                # On macOS, an inherited DISPLAY (e.g. :0.0) may force an invalid
                # X11 path and break native SUMO-GUI startup.
                warnings.warn(
                    f"Ignoring DISPLAY={old_display!r} for SUMO-GUI on macOS.",
                    RuntimeWarning,
                )
                os.environ.pop("DISPLAY", None)
            traci.start(cmd, stdout=subprocess.DEVNULL, numRetries=10)
            self._sumo_running = True
            return
        except Exception as e:
            # On some systems (e.g. integrated terminals without display access),
            # sumo-gui fails. Fall back to headless sumo automatically.
            if self.use_gui:
                headless_bin = self._sumo_bin.replace("sumo-gui", "sumo")
                if headless_bin == self._sumo_bin:
                    headless_bin = "sumo"
                warnings.warn(
                    f"SUMO-GUI unavailable ({e}). Falling back to headless SUMO.\n"
                    "For GUI: run the demo command from Terminal.app instead.",
                    RuntimeWarning,
                )
                self.use_gui = False
                self._delay_ms = 0
                self._sumo_bin = headless_bin
                traci.start(_build_cmd(self._sumo_bin), stdout=subprocess.DEVNULL, numRetries=10)
                self._sumo_running = True
                return
            raise
        finally:
            if clear_display and old_display is not None:
                os.environ["DISPLAY"] = old_display

    def reset(self):
        self._start_sumo()
        self.current_phase      = 0
        self._arrived_total     = 0
        traci.trafficlight.setPhase(self.tl_id, _PHASE_NS_GREEN)
        for _ in range(5):
            traci.simulationStep()
        self.prev_total_waiting = self._get_total_waiting()
        return self._get_state()

    def close(self):
        if self._sumo_running:
            try:
                traci.close()
            except Exception:
                pass
            self._sumo_running = False

    def __del__(self):
        self.close()

    # ── Simulation helpers ───────────────────────────────────────────────────

    def _edge_vehicle_count(self, edge_id: str) -> int:
        try:
            return traci.edge.getLastStepVehicleNumber(edge_id)
        except Exception:
            return 0

    def _edge_waiting_count(self, edge_id: str) -> int:
        try:
            return traci.edge.getLastStepHaltingNumber(edge_id)
        except Exception:
            return 0

    def _get_total_waiting(self) -> float:
        try:
            return float(sum(
                traci.lane.getLastStepHaltingNumber(lid)
                for lid in traci.lane.getIDList()
            ))
        except Exception:
            return 0.0

    def _get_total_vehicles(self) -> float:
        try:
            return float(traci.vehicle.getIDCount())
        except Exception:
            return 0.0

    def _get_state(self):
        veh_counts  = [self._edge_vehicle_count(e) for e in _APPROACHES]
        wait_counts = [self._edge_waiting_count(e) for e in _APPROACHES]
        total_veh   = self._get_total_vehicles()
        total_wait  = self._get_total_waiting()
        return veh_counts + wait_counts + [total_veh, total_wait, self.current_phase]

    # ── Phase control ────────────────────────────────────────────────────────

    def _set_green_phase(self, action: int):
        """
        Set green phase (0=NS, 1=EW), inserting a yellow phase when switching.
        Maps action → SUMO phase index: 0→0, 1→2.
        """
        target_phase = _PHASE_NS_GREEN if action == 0 else _PHASE_EW_GREEN

        if action != self.current_phase:
            # Insert yellow before switching
            yellow = _PHASE_NS_YELLOW if self.current_phase == 0 else _PHASE_EW_YELLOW
            traci.trafficlight.setPhase(self.tl_id, yellow)
            for _ in range(_YELLOW_STEPS):
                traci.simulationStep()

        traci.trafficlight.setPhase(self.tl_id, target_phase)
        self.current_phase = action

    # ── Reward ───────────────────────────────────────────────────────────────

    def _compute_reward(self) -> float:
        current_waiting  = self._get_total_waiting()
        current_vehicles = self._get_total_vehicles()

        # Identical formulation to CityFlow env for apples-to-apples comparison
        reward = (self.prev_total_waiting - current_waiting) - 0.05 * current_vehicles
        reward = float(np.clip(reward, -10.0, 10.0))

        self.prev_total_waiting = current_waiting
        return reward

    # ── Step ─────────────────────────────────────────────────────────────────

    def step(self, action: int):
        self._set_green_phase(action)

        for _ in range(self.action_duration):
            self._arrived_total += traci.simulation.getArrivedNumber()
            traci.simulationStep()

        next_state = self._get_state()
        reward     = self._compute_reward()
        done       = traci.simulation.getMinExpectedNumber() <= 0

        return next_state, reward, done

    def get_throughput(self) -> int:
        """Total vehicles that completed their route this episode."""
        return self._arrived_total
