"""
SUMO/TraCI traffic environment — mirrors the CityFlow TrafficEnv interface.

Prerequisites:
    1. pip install traci sumolib       (already installed)
    2. brew install sumo               (installs the simulator binary)
    3. cd data/sumo && bash setup_sumo.sh   (generates cross.net.xml via netconvert)

State (11 dims):  [veh_N, veh_S, veh_E, veh_W,
                   wait_N, wait_S, wait_E, wait_W,
                   total_veh, total_wait, current_phase]
Action:           0 = NS green,  1 = EW green
Reward:           same formulation as CityFlow env for fair comparison
"""

import os
import subprocess  # noqa: F401 — used for subprocess.DEVNULL in traci.start

import numpy as np

try:
    import traci
except ImportError:
    raise ImportError("traci not found. Install with: pip install traci sumolib")

# ── Paths ─────────────────────────────────────────────────────────────────────
_DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data", "sumo")
_NET_FILE  = os.path.join(_DATA_DIR, "cross.net.xml")
_CFG_FILE  = os.path.join(_DATA_DIR, "cross.sumocfg")

# Phase indices as generated by netconvert for a simple cross intersection
# 0 = NS green, 1 = NS yellow, 2 = EW green, 3 = EW yellow
_PHASE_NS_GREEN  = 0
_PHASE_NS_YELLOW = 1
_PHASE_EW_GREEN  = 2
_PHASE_EW_YELLOW = 3
_YELLOW_STEPS    = 3     # 3 sim-seconds of yellow on phase switch

# Approach edge IDs (must match cross.edg.xml)
_APPROACHES = ["N2C", "S2C", "E2C", "W2C"]


class SumoTrafficEnv:
    def __init__(
        self,
        cfg_file: str = None,
        tl_id:    str = "C",
        use_gui:  bool = False,
        action_duration: int = 10,
        delay_ms: int = 0,
    ):
        self.cfg_file        = cfg_file or _CFG_FILE
        self.tl_id           = tl_id
        self.use_gui         = use_gui
        self.action_duration = action_duration

        self.current_phase       = 0
        self.prev_total_waiting  = 0.0
        self._sumo_running       = False
        self._delay_ms           = delay_ms
        self._arrived_total      = 0   # cumulative throughput tracker

        # Verify network exists
        if not os.path.exists(_NET_FILE):
            raise FileNotFoundError(
                f"SUMO network not found at {_NET_FILE}\n"
                "Generate it with:\n"
                "  cd data/sumo && bash setup_sumo.sh\n"
                "(requires: brew install sumo)"
            )

        # Locate the sumo binary and resolve SUMO_HOME
        binary = "sumo-gui" if use_gui else "sumo"
        _SUMO_SEARCH = [
            os.environ.get("SUMO_HOME", ""),
            "/Library/Frameworks/EclipseSUMO.framework/Versions/1.26.0/EclipseSUMO",
            "/Library/Frameworks/EclipseSUMO.framework/Versions/Current/EclipseSUMO",
            "/opt/homebrew/share/sumo",
            "/usr/local/share/sumo",
        ]
        self._sumo_bin  = binary   # fallback: rely on PATH
        self._sumo_home = os.environ.get("SUMO_HOME", "")
        for candidate_home in _SUMO_SEARCH:
            if candidate_home and os.path.isfile(os.path.join(candidate_home, "bin", binary)):
                self._sumo_bin  = os.path.join(candidate_home, "bin", binary)
                self._sumo_home = candidate_home
                break

    # ── Lifecycle ────────────────────────────────────────────────────────────

    def _start_sumo(self):
        if self._sumo_running:
            try:
                traci.close()
            except Exception:
                pass
            self._sumo_running = False

        # Set SUMO_HOME in the current process so the subprocess inherits it
        if self._sumo_home:
            os.environ["SUMO_HOME"] = self._sumo_home

        cmd = [
            self._sumo_bin,
            "-c", self.cfg_file,
            "--no-warnings",
            "--no-step-log",
            "--time-to-teleport", "-1",
        ]
        if self._delay_ms > 0:
            cmd += ["--delay", str(self._delay_ms)]
        traci.start(cmd, stdout=subprocess.DEVNULL)
        self._sumo_running = True

    def reset(self):
        self._start_sumo()
        self.current_phase      = 0
        self._arrived_total     = 0
        traci.trafficlight.setPhase(self.tl_id, _PHASE_NS_GREEN)
        for _ in range(5):
            traci.simulationStep()
        self.prev_total_waiting = self._get_total_waiting()
        return self._get_state()

    def close(self):
        if self._sumo_running:
            try:
                traci.close()
            except Exception:
                pass
            self._sumo_running = False

    def __del__(self):
        self.close()

    # ── Simulation helpers ───────────────────────────────────────────────────

    def _edge_vehicle_count(self, edge_id: str) -> int:
        try:
            return traci.edge.getLastStepVehicleNumber(edge_id)
        except Exception:
            return 0

    def _edge_waiting_count(self, edge_id: str) -> int:
        try:
            return traci.edge.getLastStepHaltingNumber(edge_id)
        except Exception:
            return 0

    def _get_total_waiting(self) -> float:
        try:
            return float(sum(
                traci.lane.getLastStepHaltingNumber(lid)
                for lid in traci.lane.getIDList()
            ))
        except Exception:
            return 0.0

    def _get_total_vehicles(self) -> float:
        try:
            return float(traci.vehicle.getIDCount())
        except Exception:
            return 0.0

    def _get_state(self):
        veh_counts  = [self._edge_vehicle_count(e) for e in _APPROACHES]
        wait_counts = [self._edge_waiting_count(e) for e in _APPROACHES]
        total_veh   = self._get_total_vehicles()
        total_wait  = self._get_total_waiting()
        return veh_counts + wait_counts + [total_veh, total_wait, self.current_phase]

    # ── Phase control ────────────────────────────────────────────────────────

    def _set_green_phase(self, action: int):
        """
        Set green phase (0=NS, 1=EW), inserting a yellow phase when switching.
        Maps action → SUMO phase index: 0→0, 1→2.
        """
        target_phase = _PHASE_NS_GREEN if action == 0 else _PHASE_EW_GREEN

        if action != self.current_phase:
            # Insert yellow before switching
            yellow = _PHASE_NS_YELLOW if self.current_phase == 0 else _PHASE_EW_YELLOW
            traci.trafficlight.setPhase(self.tl_id, yellow)
            for _ in range(_YELLOW_STEPS):
                traci.simulationStep()

        traci.trafficlight.setPhase(self.tl_id, target_phase)
        self.current_phase = action

    # ── Reward ───────────────────────────────────────────────────────────────

    def _compute_reward(self) -> float:
        current_waiting  = self._get_total_waiting()
        current_vehicles = self._get_total_vehicles()

        # Identical formulation to CityFlow env for apples-to-apples comparison
        reward = (self.prev_total_waiting - current_waiting) - 0.05 * current_vehicles
        reward = float(np.clip(reward, -10.0, 10.0))

        self.prev_total_waiting = current_waiting
        return reward

    # ── Step ─────────────────────────────────────────────────────────────────

    def step(self, action: int):
        self._set_green_phase(action)

        for _ in range(self.action_duration):
            self._arrived_total += traci.simulation.getArrivedNumber()
            traci.simulationStep()

        next_state = self._get_state()
        reward     = self._compute_reward()
        done       = traci.simulation.getMinExpectedNumber() <= 0

        return next_state, reward, done

    def get_throughput(self) -> int:
        """Total vehicles that completed their route this episode."""
        return self._arrived_total
